### ISSUE TITLE
this.baseURL = new URL(`/v${this.v}`, baseURL); 

### ISSUE THREAD

**Issue by wandersouzadev** [zuritor/jikanjs#9]
c:\Users\nyste\Desktop\bot\node_modules\jikanjs\lib\util\Settings.js:23
        this.baseURL = new URL(`/v${this.v}`, baseURL);
                           ^
ReferenceError: URL is not defined

`const jikanjs  = require('jikanjs'); // Uses per default the API version 3

jikanjs.loadAnime(19815, 'episodes').then((response) => {
    response.episodes.forEach(element => {
        console.log(`${element.episode_id}: ${element.title} - ${element.title_romanji} - ${element.title_japanese}`);
    })
}).catch((err) => {
    console.error(err); // in case a error happens
});`

**Comment by zuritor** [comment]
Can you please provide a little more information like node version and platform because I am not able to reproduce your Problem.

**Comment by wandersouzadev** [comment]
Sorry, the problem was the version of nodejs, thank you.
